frr version 10.2.1
frr defaults datacenter
hostname spine1
!
interface lo
 ip address 10.255.0.101/32
!
interface eth1
 ip address 10.0.1.0/31
!
interface eth2
 ip address 10.0.2.0/31
!
router bgp 65100
 bgp router-id 10.255.0.101
 no bgp ebgp-requires-policy
 neighbor 10.0.1.1 remote-as 65011
 neighbor 10.0.2.1 remote-as 65012
 !
 address-family ipv4 unicast
  network 10.255.0.101/32
  maximum-paths 8
 exit-address-family
!
