frr version 10.2.1
frr defaults datacenter
hostname spine2
!
interface lo
 ip address 10.255.0.102/32
!
interface eth1
 ip address 10.0.11.0/31
!
interface eth2
 ip address 10.0.12.0/31
!
router bgp 65100
 bgp router-id 10.255.0.102
 no bgp ebgp-requires-policy
 neighbor 10.0.11.1 remote-as 65011
 neighbor 10.0.12.1 remote-as 65012
 !
 address-family ipv4 unicast
  network 10.255.0.102/32
  maximum-paths 8
 exit-address-family
! 


