frr version 10.2.1
frr defaults datacenter
hostname leaf2
!
interface lo
 ip address 10.255.0.12/32
!
interface eth1
 ip address 10.0.2.1/31
!
interface eth2
 ip address 192.168.12.1/24
!
interface eth3
 ip address 10.0.12.1/31
!
router bgp 65012
 bgp router-id 10.255.0.12
 no bgp ebgp-requires-policy
 neighbor 10.0.2.0 remote-as 65100
 neighbor 10.0.12.0 remote-as 65100
 !
 address-family ipv4 unicast
  network 10.255.0.12/32
  network 192.168.12.0/24
  maximum-paths 8
 exit-address-family
!
