frr version 10.2.1
frr defaults datacenter
hostname leaf1
!
interface lo
 ip address 10.255.0.11/32
!
interface eth1
 ip address 10.0.1.1/31
!
interface eth2
 ip address 192.168.11.1/24
!
interface eth3
 ip address 10.0.11.1/31
!
router bgp 65011
 bgp router-id 10.255.0.11
 no bgp ebgp-requires-policy
 neighbor 10.0.1.0 remote-as 65100
 neighbor 10.0.11.0 remote-as 65100
 !
 address-family ipv4 unicast
  network 10.255.0.11/32
  network 192.168.11.0/24
  maximum-paths 8
 exit-address-family
!
